In [1]:
import numpy as np
from pyDatalog import pyDatalog
from pyDatalog import pyEngine

In [2]:
def Product(x, y):
    z = []
    for x1 in x:
        for y1 in y.T:
            z.append(max(np.multiply(x1, y1)))
    return np.array(z).reshape((x.shape[0], y.shape[1]))

In [5]:
kl = np.array([[0, 0.2, 0.7, 0.8], [0, 0.3, 0.7, 0.5], [0.5, 0.5, 0.5, 0.5], [0.7, 0.4, 0.4, 0.6], [0.7, 0.7, 0.3, 0.3]])
vl = np.array([[0, 0.3, 0.3, 0.7, 0], [0.3, 0.1, 0.7, 0.3, 0.8], [0.8, 0.6, 0.5, 0.4, 0.3], [0.8, 0.8, 0.5, 0.6, 0.2]])
print(kl)
print(vl)

[[ 0.   0.2  0.7  0.8]
 [ 0.   0.3  0.7  0.5]
 [ 0.5  0.5  0.5  0.5]
 [ 0.7  0.4  0.4  0.6]
 [ 0.7  0.7  0.3  0.3]]
[[ 0.   0.3  0.3  0.7  0. ]
 [ 0.3  0.1  0.7  0.3  0.8]
 [ 0.8  0.6  0.5  0.4  0.3]
 [ 0.8  0.8  0.5  0.6  0.2]]


In [6]:
print(Product(kl, vl))

[[ 0.64  0.64  0.4   0.48  0.21]
 [ 0.56  0.42  0.35  0.3   0.24]
 [ 0.4   0.4   0.35  0.35  0.4 ]
 [ 0.48  0.48  0.3   0.49  0.32]
 [ 0.24  0.24  0.49  0.49  0.56]]


In [1]:
import pandas as pd

kolduny = pd.DataFrame({'Eff_of_mag' : [0., 0., 0.5, 0.7, 0.7],
                        'Eff_of_phys' : [0.2, 0.3, 0.5, 0.4, 0.7],
                        'Vos_mag' : [0.7, 0.7, 0.5, 0.4, 0.3],
                        'Vos_phys' : [0.8, 0.5, 0.5, 0.6, 0.3],
                        'Price' : [85., 90., 200., 290., 490.]},
                       index = ('skelet', 'zomby', 'vampire', 'vedma', 'dragon'))
print (kolduny)

volshebniki = pd.DataFrame({'Eff_of_mag' : [0., 0.3, 0.3, 0.7, 0.],
                        'Eff_of_phys' : [0.3, 0.1, 0.7, 0.3, 0.8],
                        'Vos_mag' : [0.8, 0.6, 0.5, 0.4, 0.3],
                        'Vos_phys' : [0.8, 0.8, 0.5, 0.6, 0.2],
                        'Price' : [90., 100., 190., 200., 390.]},
                       index = ('krest', 'elf', 'rycar', 'fei', 'titan'))
print (volshebniki)

         Eff_of_mag  Eff_of_phys  Price  Vos_mag  Vos_phys
skelet          0.0          0.2   85.0      0.7       0.8
zomby           0.0          0.3   90.0      0.7       0.5
vampire         0.5          0.5  200.0      0.5       0.5
vedma           0.7          0.4  290.0      0.4       0.6
dragon          0.7          0.7  490.0      0.3       0.3
       Eff_of_mag  Eff_of_phys  Price  Vos_mag  Vos_phys
krest         0.0          0.3   90.0      0.8       0.8
elf           0.3          0.1  100.0      0.6       0.8
rycar         0.3          0.7  190.0      0.5       0.5
fei           0.7          0.3  200.0      0.4       0.6
titan         0.0          0.8  390.0      0.3       0.2
